---
title: "Untitled"
author: "MITCH"
date: "4/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(gcookbook)
library(corrplot)
library(igraph)
library(rgl)
library(grid)
library(vcd)
library(MASS)
library(maps)
library(plyr)
library(maptools)


```


```{r}
predictgrid <- function(model, xvar, yvar, zvar, res = 16, type = NULL) {
 
  xrange <- range(model$model[[xvar]])
  yrange <- range(model$model[[yvar]])
  newdata <- expand.grid(x = seq(xrange[1], xrange[2], length.out = res),
                         y = seq(yrange[1], yrange[2], length.out = res))
  names(newdata) <- c(xvar, yvar)
  newdata[[zvar]] <- predict(model, newdata = newdata, type = type)
  newdata
}

df2mat <- function(p, xvar = NULL, yvar = NULL, zvar = NULL) {
  if (is.null(xvar)) xvar <- names(p)[1]
  if (is.null(yvar)) yvar <- names(p)[2]
  if (is.null(zvar)) zvar <- names(p)[3]

  x <- unique(p[[xvar]])
  y <- unique(p[[yvar]])
  z <- matrix(p[[zvar]], nrow = length(y), ncol = length(x))

  m <- list(x, y, z)
  names(m) <- c(xvar, yvar, zvar)
  m
}


interleave <- function(v1, v2)  as.vector(rbind(v1,v2))

m <- mtcars


mod <- lm(mpg ~ wt + disp + wt:disp, data = m)

m$pred_mpg <- predict(mod)


mpgrid_df <- predictgrid(mod, "wt", "disp", "mpg")
mpgrid_list <- df2mat(mpgrid_df)


plot3d(m$wt, m$disp, m$mpg, type="s", size=0.5, lit=FALSE)


spheres3d(m$wt, m$disp, m$pred_mpg, alpha=0.4, type="s", size=0.5, lit=FALSE)


segments3d(interleave(m$wt,   m$wt),
           interleave(m$disp, m$disp),
           interleave(m$mpg,  m$pred_mpg),
           alpha=0.4, col="red")


surface3d(mpgrid_list$wt, mpgrid_list$disp, mpgrid_list$mpg,
          alpha=0.4, front="lines", back="lines")
```

```{r}
plot3d(mtcars$wt, mtcars$disp, mtcars$mpg,
       xlab = "", ylab = "", zlab = "",
       axes = FALSE,
       size=.5, type="s", lit=FALSE)
```

```{r}
spheres3d(m$wt, m$disp, m$pred_mpg, alpha=0.4, type="s", size=0.5, lit=FALSE)

segments3d(interleave(m$wt,   m$wt),
           interleave(m$disp, m$disp),
           interleave(m$mpg,  m$pred_mpg),
           alpha=0.4, col="red")

surface3d(mpgrid_list$wt, mpgrid_list$disp, mpgrid_list$mpg,
          alpha=0.4, front="lines", back="lines")

rgl.bbox(color="grey50",          
         emission="grey50",       
         xlen=0, ylen=0, zlen=0)

rgl.material(color="black")

axes3d(edges=c("x--", "y+-", "z--"),
       ntick=6,                      
       cex=.75)  

mtext3d("Weight",       edge="x--", line=2)
mtext3d("Displacement", edge="y+-", line=3)
mtext3d("MPG",          edge="z--", line=3)


```






```{r}



plot3d(mtcars$wt, mtcars$disp, mtcars$mpg, type="s", size=0.75, lit=FALSE)

rgl.snapshot('3dplot.png', fmt='png')

rgl.postscript('figs/miscgraph/3dplot.pdf', fmt='pdf')

rgl.postscript('figs/miscgraph/3dplot.ps', fmt='ps')

view <- par3d("userMatrix")


par3d(userMatrix = view)


library(rgl)
plot3d(mtcars$wt, mtcars$disp, mtcars$mpg, type="s", size=0.75, lit=FALSE)

play3d(spin3d())

play3d(spin3d(axis=c(1,0,0), rpm=4), duration=20)


movie3d(spin3d(axis=c(0,0,1), rpm=4), duration=15, fps=50)



```

### Section 13.10. Animating a Three-Dimensional Plot

```{r}

library(rgl)
plot3d(mtcars$wt, mtcars$disp, mtcars$mpg, type="s", size=0.75, lit=FALSE)

play3d(spin3d())

play3d(spin3d(axis=c(1,0,0), rpm=4), duration=20)

movie3d(spin3d(axis=c(0,0,1), rpm=4), duration=15, fps=50)










```

### Section 13.11. Creating a Dendrogram

```{r}
c2 <- subset(countries, Year==2009)


c2 <- c2[complete.cases(c2), ]

set.seed(201)
c2 <- c2[sample(1:nrow(c2), 25), ]

c2

rownames(c2) <- c2$Name
c2 <- c2[,4:7]
c2

c3 <- scale(c2)

hc <- hclust(dist(c3))

plot(hc)

plot(hc, hang = -1)





```